service: agile-ticket-description-generator

frameworkVersion: '3'

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!ui/**'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  httpApi:
    cors: true
  iamRoleStatements:
    - ${file(iam/BedrockModelIAM.yml):BedrockModelIAM}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    timeout: 29

plugins:
  - serverless-wsgi
  - serverless-python-requirements
