service: agile-ticket-description-generator

frameworkVersion: '3'

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!ui/**'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - bedrock:InvokeModel
      Resource: arn:aws:bedrock:${self:provider.region}::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    timeout: 29

plugins:
  - serverless-wsgi
  - serverless-python-requirements
