service: agile-ticket-description-generator

frameworkVersion: '3'

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!ui/**'

custom:
  wsgi:
    app: app.app
  PromptLogsTable:
    name: !Ref PromptLogsTable
    arn: !GetAtt PromptLogsTable.Arn
  PromptLogsQueue:
    name: !Ref PromptLogsQueue
    arn: !GetAtt PromptLogsQueue.Arn
    url: !GetAtt PromptLogsQueue.QueueUrl

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - ${file(iam/BedrockModelIAM.yml):BedrockModelIAM}

resources:
  Resources:
    PromptLogsTable: ${file(resources/PromptLogsTable.yml):PromptLogsTable}
    PromptLogsQueue: ${file(resources/PromptLogsQueue.yml):PromptLogsQueue}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    timeout: 29
  promptLogHandler:
    handler: functions/prompt_log_handler.handler
    events:
      - sqs:
          batchSize: 1
          arn: ${self:custom.PromptLogsQueue.arn}
    environment:
      PROMPT_LOGS_TABLE: ${self:custom.PromptLogsTable.name}

plugins:
  - serverless-wsgi
  - serverless-python-requirements
